name: docs

on:
  push:
    branches: [ master ]
    paths: [ '**.java', '.github/workflows/docs.yml', 'docs/index.html' ]
  pull_request:
    branches: [ master ]
    paths: [ '**.java', '.github/workflows/docs.yml', 'docs/index.html' ]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 

    - name: Set up JDK 1.11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build docs with Maven
      run: mvn javadoc:javadoc

    - name: Copy to Documentation Website Location
      run: |
        rm -rf docs/api
        cp -rf target/site/apidocs/. docs/api	

    - name: Tidy up the javadocs
      id: tidy
      uses: cicirello/javadoc-cleanup@v1
      with:
        base-url-path: https://jpt.cicirello.org/
        path-to-root: docs
        user-defined-block: |
          <link rel="icon" href="/images/favicon.svg" sizes="any" type="image/svg+xml">

    - name: Log javadoc-cleanup output
      run: |
        echo "modified-count = ${{ steps.tidy.outputs.modified-count }}"

    - name: Commit documentation changes
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'Vincent A Cicirello'
          git config --global user.email 'cicirello@users.noreply.github.com'
          git add -A
          git commit -m "Automated API website updates."
        fi

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://jpt.cicirello.org/
        path-to-root: docs

    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

    - name: Create Pull Request
      if: ${{ github.event_name == 'push' }}
      uses: peter-evans/create-pull-request@v3.10.1
      with:
        title: "Automated API website updates."
        body: > 
          Automated changes to the API documentation website.
          Documentation updated via javadoc. Sitemap updated by 
          the [generate-sitemap](https://github.com/cicirello/generate-sitemap) 
          GitHub action.  Automated pull-request generated by 
          [create-pull-request](https://github.com/peter-evans/create-pull-request) 
          GitHub action.
        commit-message: "Automated API documentation website updates."
        author: Vincent A Cicirello <cicirello@users.noreply.github.com>
        committer: Vincent A Cicirello <cicirello@users.noreply.github.com>
        branch: create-pull-request/docs
        delete-branch: true
